added java transaction processor and 'clear jar' feature
danintel/sawtooth-cookiejar pull request #2
Opened 2018-08-10 08:59 UTC by raneja14

added java transaction processor and 'clear jar' feature

Signed-off-by: raghav.aneja <raghav.aneja@intel.com>

2018-08-28 06:57 UTC, raneja14 commented
@danintel Please review the changes and merge to your repository

2018-08-28 17:58 UTC, danintel requested changes

2018-08-28 17:58 UTC, danintel commented on javaprocessor/src/main/java/cookiejar/processor/CookieJarProcessor.java
> +			 logger.info("No cookie jar availble");
s/availble/available/

2018-08-28 17:58 UTC, danintel commented on javaprocessor/src/main/java/cookiejar/processor/CookieJarProcessor.java
> +	     // Split the csv utf-8 string
Indent this line the same as the other lines.

2018-08-28 17:58 UTC, danintel commented on javaprocessor/src/main/java/cookiejar/processor/CookieJarProcessor.java
> + * This is the place where you implement your transaction specific logic(Inside apply() method
Delete this line (line 41)

2018-08-28 17:58 UTC, danintel commented on javaprocessor/src/main/java/cookiejar/processor/CookieJarProcessor.java
> +        // and user signer public key
Indent this line (137) the same as the other lines.

2018-10-29 17:18 UTC, danintel approved these changes
I'll make the corrections and changes I previously suggested in a follow-up push.

2018-10-29 17:19 UTC, merged